### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [cxcandid/GeorefExtension#1]
Hi @cxcandid, Have you considered integrating these changes as part of the main georeferencer plugin? For a start, you could write to the QGIS developer mailing list to describe the plugin you have done and ask if they think it will be worthwhile to incorporate into the core plugin

**Comment by cxcandid** [comment]
@NyakudyaA I'm not sure if the plugin fulfills all the criteria to be included in core QGIS. I first wanted to make it available as an experimental plugin to let the community test it. I would like to wait for feedback before discussing it with the developers.

**Comment by NyakudyaA** [comment]
@cxcandid The idea is not to have it included in the core directly as it is. As a start to even gather feedback from users and also make people aware, This could be a good conversation starter, in the meantime I have approved the plugin
